# Generated by Django 4.1.2 on 2022-11-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgcreate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputhm',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
